apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: ngnix-app
spec:
  selector:
    matchLabels:
      app: ngnix-app
  replicas: 2
  template:
    metadata:
      labels:
        app: ngnix-app
    spec:
      containers:
      - name: ngnix
        image: ngnix
        ports:
        - containerPort: 80
