apiVersion: v1
kind: Pod
metadata:
   name: liveliness-check
   labels:
      test: liveliness
spec:
   containers:
   - name: k8-image
     image: k8s.gcr.io/busybox
     args:
     - bin/sh
     - -c
     - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
     livenessProbe:
        exec:
           command:
           - cat
           - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
