apiVersion: batch/v1
kind: Job
metadata:
  name: job-backofflimit
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: job-backofflimit
        image: perl
        args:
        - /bin/sh
        - -c
        - date; echo sleeping; sleep 5s; exit 1;
      restartPolicy: OnFailure
