apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  imagePullSecrets:
      - name: imgcred
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: pv-container
      image: 172.27.5.153:8082/nginx/nginx:latest
      args:
        - /bin/sh
        - -c
        - echo container started; echo date; echo exiting;
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-storage
